spring:
  mail:
    host: smtp.timeweb.ru
    port: 465
    username: collector-web@mogcommunity.ru
    password: popugai_oldspays1
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true
          starttls.enable: false
  application:
    name: collector-web
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/%D1%81ollector_database
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true

