spring:
  application:
    name: collector-web
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/%D1%81ollector_database
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true

